# Generated by Django 3.2.3 on 2021-08-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guser', '0002_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
